server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${TIERDYOL_POSTGRE_URL}
    username: ${TIERDYOL_POSTGRE_USERNAME}
    password: ${TIERDYOL_POSTGRE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  mail:
    host: smtp.gmail.com
    port: 587
    username: ${TIERDYOL_MAIL_USERNAME}
    password: ${TIERDYOL_MAIL_PASSWORD}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

logging:
  file:
    name: proje.log
  level:
    root: info
  logback:
    rollingpolicy:
      max-file-size: 2MB


java15:
  jwt:
    secret-key: ${TIERDYOL_JWT_SECRETKEY}
    issuer: ${TIERDYOL_JWT_ISSUER}