server:
  port: 9090

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${TIERDYOL_POSTGRE_URL}
    username: ${TIERDYOL_POSTGRE_USERNAME}
    password: ${TIERDYOL_POSTGRE_PASSWORD}
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

#logging:
#  file:
#    name: proje.log
#  level:
#    root: info
#    com.ajwalker: trace
#  logback:
#    rollingpolicy:
#      max-file-size: 2MB


java15:
  jwt:
    secret-key: ${TIERDYOL_JWT_SECRETKEY}
    issuer: ${TIERDYOL_JWT_ISSUER}